server:
  port: 8080

spring:
  data:
    redis:
      url: redis://localhost:6379
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5437/mydatabase
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none   # Use 'none' or 'validate' since Flyway manages your schema
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql.BasicBinder: error
    org.springframework.cache: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5           # try up to 5 times
        wait-duration: 200ms      # pause 200ms between retries
        retry-exceptions:
          - org.springframework.dao.PessimisticLockingFailureException
    instances:
      taskService:               # name must match the @Retry name below
        max-attempts: 5                   # total tries = 1 initial + 4 retries
        retry-exceptions:
          - org.springframework.dao.PessimisticLockingFailureException
        ignore-exceptions:
          - java.util.NoSuchElementException

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    loggers:
      enabled: true
