server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/mydatabase
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none   # Use 'none' or 'validate' since Flyway manages your schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
