server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/mydatabase
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none   # Use 'none' or 'validate' since Flyway manages your schema
    show-sql: true


  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql.BasicBinder: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    loggers:
      enabled: true
